package com.floweytech.agrotrack.reports.domain.model.queries;


import com.floweytech.agrotrack.reports.shared.domain.model.valueobjects.ProfileId;

/**
 * Get All Reports By Profile Id Query
 * @summary
 * Query record used to request all reports generated by a specific profile (user).
 *
 * @param profileId The profile ID to filter the reports.
 * @author FloweyTech developer team
 */
public record GetAllReportsByProfileIdQuery(ProfileId profileId) {
}
